POST http://localhost:8080/api/v1/student
content-type: application/json

{
    "name": "Ngan hue",
    "email": "ngahue@gmail.com",
    "dob": "1999-12-17"
}

###

GET http://localhost:8080/api/v1/student

###
DELETE http://localhost:8080/api/v1/student/1

###
PUT http://localhost:8080/api/v1/student/1?name=NganHue&email=NganHue@gmail.com
content-type: application/json
